# Generated by Django 2.2.3 on 2020-10-03 22:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='food',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Nombre')),
                ('calories', models.IntegerField(verbose_name='Calorias')),
            ],
            options={
                'verbose_name': 'Alimento',
                'verbose_name_plural': 'Alimentos',
            },
        ),
        migrations.CreateModel(
            name='meal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.CharField(choices=[('Lunes', 'Lunes'), ('Martes', 'Martes'), ('Miercoles', 'Miercoles'), ('Jueves', 'Jueves'), ('Viernes', 'Viernes'), ('Sabado', 'Sabado'), ('Domingo', 'Domingo')], default='Lunes', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('almuerzo', models.ManyToManyField(blank=True, related_name='Almuerzo', to='Blog.food', verbose_name='Almuerzo')),
                ('cena', models.ManyToManyField(blank=True, related_name='Cena', to='Blog.food', verbose_name='Cena')),
                ('desayuno', models.ManyToManyField(blank=True, related_name='Desayuno', to='Blog.food', verbose_name='Desayuno')),
                ('snacks', models.ManyToManyField(blank=True, related_name='Snack', to='Blog.food', verbose_name='Snack')),
                ('user', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Registros',
            },
        ),
    ]
