# Generated by Django 2.2.3 on 2020-10-05 17:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0002_auto_20201003_1718'),
    ]

    operations = [
        migrations.CreateModel(
            name='hora',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hora_dia', models.CharField(max_length=20, verbose_name='HoraDelDia')),
            ],
            options={
                'verbose_name': 'Hora del dia',
            },
        ),
        migrations.RemoveField(
            model_name='meal',
            name='almuerzo',
        ),
        migrations.RemoveField(
            model_name='meal',
            name='cena',
        ),
        migrations.RemoveField(
            model_name='meal',
            name='desayuno',
        ),
        migrations.RemoveField(
            model_name='meal',
            name='snacks',
        ),
        migrations.AddField(
            model_name='meal',
            name='hora',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='Blog.hora'),
        ),
    ]
