# Generated by Django 2.2.3 on 2020-10-05 17:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0003_auto_20201005_1233'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meal',
            name='hora',
            field=models.ForeignKey(default='0', on_delete=django.db.models.deletion.CASCADE, to='Blog.hora'),
        ),
    ]
