# Generated by Django 2.2.3 on 2020-10-05 17:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0004_auto_20201005_1239'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meal',
            name='hora',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='Blog.hora'),
        ),
    ]
